server:
  port: 7000
spring:
  application:
    name: plataformae
  datasource:
    url: "jdbc:postgresql://localhost:5432/plataformae"
    username: "postgres"
    password: "admin"
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariPool
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
jwt:
  secret: "kaS1ElkVdZs9e6Z2mdeFK4jCddtSKZvNZi/yMZtUBzc="
  expiration: 604800000

app:
  messages:
    login-success: "Login exitoso"
    invalid-credentials: "Usuario o contraseña invalidos"
    error-occurred: "ha ocurrido un error"
    usuario-creado: "Usuario creado con éxito"
    usuario-ya-existe: "El numero de identificación ingresado ya se encuentra registrado"
    celular-ya-existe: "El celular ingresado ya se encuentra asociado a otro usuario"

logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{transactionId}] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%X{transactionId}] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
    level:
      root: trace
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 1

auth:
  prefixes: "/api/auth/,/plataformae/api/auth/"